name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main  # O la rama en la que deseas ejecutar este pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Paso 3: Iniciar sesión en Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Paso 4: Construir la imagen de Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/clrecordatoriobackend:latest   -f ./clrecordatoriobackend/Dockerfile ./clrecordatoriobackend

    # Paso 5: Etiquetar y subir la imagen a ACR
    - name: Push Docker image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/clrecordatoriobackend:latest
